ifneq ($(KERNELRELEASE),)
# kbuild part of Makefile
obj-m := hello_lab6.o
ccflags-y += -g
else
# Normal Makefile
KDIR ?= /lib/modules/$(shell uname -r)/build

default:
	$(MAKE) -C $(KDIR) M=$$PWD
	cp hello_lab6.ko hello_lab6.ko.unstripped
	$(CROSS_COMPILE)strip -g hello_lab6.ko

clean:
	$(MAKE) -C $(KDIR) M=$(PWD) clean

%.s %.i: %.c
	$(MAKE) -C $(KDIR) M=$$PWD $@
Endif
